<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "peec_extension"
 *
 * Auto generated by Extension Builder 2020-06-23
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'PEEC Extension',
    'description' => 'This extension is built for the website of the research group peec. 
It contains the connections and the interplay between the components employees, companies, projects and publications.',
    'category' => 'plugin',
    'author' => 'Daniel Saiz, Matthias Kohler',
    'author_email' => 'daniel.saiz@gmx.at, Matthias.Kohler@gmx.de',
    'state' => 'alpha',
    'uploadfolder' => 1,
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '9.5.0-9.5.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
